Create artifact suppression preprocessor
SpikeInterface/spiketoolkit pull request #483
Opened 2021-04-24 05:42 UTC by timsainb

This is a simple preprocessor that I've been using on my data. It looks for unreasonably high amplitude events, and removes them, filling with either zeros, or noise matched to the data. Sometimes, with very long chronic recordings, the tether can get a bit loose, and there will be noise artifacts or motion artifacts in the data that mess with different sorting algorithms.  I've been using it in my chronic recordings and it helps in salvaging recordings that have small sections of corrupted data.

2021-04-26 09:15 UTC, samuelgarcia commented
Hi @timsainb
spikeinetrface is in a big refactoring process.
Please have a look here:
https://github.com/SpikeInterface/spikeinterface
Could you also make a similar  PR directly there ?

2021-04-30 07:41 UTC, alejoe91 requested changes
Hi @timsainb 

Thank you so much for this and sorry for my delay in reviewing. I have a few comments :)

Also, can you add a test for completeness here: https://github.com/SpikeInterface/spiketoolkit/blob/master/spiketoolkit/tests/test_preprocessing.py?

2021-04-30 07:41 UTC, alejoe91 commented on spiketoolkit/preprocessing/suppress_artifacts.py
> +    preprocessor_name = "Clip"
```suggestion
    preprocessor_name = "ArtifactSuppression"
```

2021-04-30 07:41 UTC, alejoe91 commented on spiketoolkit/preprocessing/suppress_artifacts.py
> +        self.has_unscaled = False
```suggestion
```

Already taken car of by base (https://github.com/SpikeInterface/spiketoolkit/blob/master/spiketoolkit/preprocessing/basepreprocessorrecording.py#L22-L25)

2021-04-30 07:41 UTC, alejoe91 commented on spiketoolkit/preprocessing/suppress_artifacts.py
> +        self._kwargs = {"recording": recording.make_serialized_dict(), "thresh": thresh}
You should add all inpu args in this dict

2021-04-30 07:41 UTC, alejoe91 commented on spiketoolkit/preprocessing/suppress_artifacts.py
> +        assert return_scaled, "'clip' only supports return_scaled=True"
```suggestion
        assert return_scaled, "'suppress_artifacts' only supports return_scaled=True"
```

2021-04-30 07:41 UTC, alejoe91 commented on spiketoolkit/preprocessing/suppress_artifacts.py
> +        )
here you're convolving a boolean mask with ones. What is the purpose?

2021-04-30 07:41 UTC, alejoe91 commented on spiketoolkit/preprocessing/suppress_artifacts.py
> +                    np.random.rand(np.product(np.shape(traces))).reshape(
Can I ask you why a normal distr instead of gaussian? To avoid peaks?

2021-04-30 07:41 UTC, alejoe91 commented on spiketoolkit/preprocessing/suppress_artifacts.py
> +    rescaled_traces: ClipTracesRecording
```suggestion
    rescaled_traces: ArtifactSuppressionRecording
```

2021-04-30 07:41 UTC, alejoe91 commented on spiketoolkit/preprocessing/suppress_artifacts.py
> +        The clipped traces recording extractor object
```suggestion
        The artifact suppression recording extractor object
```

2021-05-04 00:49 UTC, timsainb commented
Thanks! I'll work on this + update for the new refactor as soon as I get the chance

2021-05-20 20:27 UTC, alejoe91 commented
@timsainb any update on this?

2021-05-20 20:45 UTC, timsainb commented
Hey, sorry, I rewrote this preprocessor for the new API taking into account your review. So maybe we can close this and I'll make a PR there.

2021-05-20 20:45 UTC, closed without merging

2021-05-20 20:46 UTC, alejoe91 commented
Sounds good! :)